import Head from 'next/head'
import Header from '../components/Header'
import TopCards from '../components/TopCards'
import LineChart from '../components/LineChart'
import RecentOrders from '@/components/RecentOrders'
import StatCard from '@/components/StatCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
         <Header />
         <div className='grid lg:grid-cols-10 gap-6 p-4 px-8'>
          <StatCard type='inventory'/>
          <StatCard type='num-inventory'/>
          <StatCard type='sales'/>
          <StatCard type='net-profit'/>
          <StatCard type='net-profit'/>


         </div>
         {/* <TopCards /> */}
         <div className='grid md:grid-cols-3 gap-4 p-4'>
          <LineChart />
          <RecentOrders />

         </div>
      </main>
    </>
  )
}
